# Generated by Django 5.1.4 on 2025-05-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupoun_applied',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
