# Generated by Django 5.1.4 on 2025-05-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_coupoun_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupoun_applied',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_applied',
            field=models.BooleanField(default=False),
        ),
    ]
