# Generated by Django 5.1.4 on 2025-05-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
